---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: linuxptp-daemon
  namespace: openshift-ptp
  annotations:
    release.openshift.io/version: "{{.ReleaseVersion}}"
spec:
  selector:
    matchLabels:
      app: linuxptp-daemon
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: linuxptp-daemon
    spec:
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - operator: Exists
      serviceAccountName: linuxptp-daemon
      containers:
      - name: linuxptp-daemon-container
        securityContext:
          privileged: true
        image: {{.Image}}
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "/usr/local/bin/ptp --alsologtostderr -v 10" ]
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: config-volume
          mountPath: /etc/linuxptp
        ports:
          - name: metrics-port
            containerPort: 9091
      volumes:
        - name: config-volume
          configMap:
            name: ptp-configmap
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: monitor-ptp
  name: monitor-ptp
  namespace: openshift-ptp
spec:
  endpoints:
    - interval: 10s
      port: metrics
  jobLabel: app
  namespaceSelector:
    matchNames:
      - openshift-ptp
  selector:
    matchLabels:
      name: ptp-monitor-service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: ptp-monitor-service
  name:  ptp-monitor-service
  namespace: openshift-ptp
spec:
  selector:
    app: linuxptp-daemon
  clusterIP: None
  ports:
    - name: metrics
      port: 9091
      protocol: TCP
      targetPort: 9091
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: openshift-ptp
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: openshift-ptp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: ptp-rules
  namespace: openshift-ptp
spec:
  groups:
    - name: ptp.rules
      rules:
        - alert: NodeOutOfPtpSync
          annotations:
            message: |
              All nodes should have ptp sync offset lower then 100
          expr: |
            openshift_ptp_max_offset_from_master > 100 or openshift_ptp_max_offset_from_master < -100
          for: 2m
          labels:
            severity: warning
